name = "multipart_form"
version = "1.0.0"
description = "Small library to generate multipart/form-data requests and parse them"
licences = ["Apache-2.0"]
repository = { type = "github", user = "siesta-cat", repo = "gleam_multipart_form" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
